server: 
 port: 8080 

spring:
  cloud:
    gateway:
      routes:
      - id : ACCOUNT-SERVICE
        uri : http://localhost:8081/
        predicates :
         - Path=/account/** 

      - id : PRODUCT-SERVICE
        uri : http://localhost:8082/
        predicates :
         - Path=/product/**

      - id : ORDER-SERVICE
        uri : http://localhost:8083/
        predicates :
         - Path=/order/**

      - id : PACKAGE-SERVICE
        uri : http://localhost:8084/
        predicates :
         - Path=/package/**

      - id : DELIVERY-SERVICE
        uri : http://localhost:8085/
        predicates :
         - Path=/delivery/**
  application:
    name: API-GATEWAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost